#!/usr/bin/env bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

# 1728, 1117
# default
# sketchybar --bar position=top height=24 blur_radius=30 color=0x40000000
# padding_right=536
# padding_right=528
bar=(
  position=top
  height=32
  blur_radius=30
  color=0x40000000
  border_color=0x40000000
  border_width=1
  padding_left=0
  padding_right=853
)
sketchybar --bar "${bar[@]}"

# sketchybar --bar \
#   position=top \
#   height=32 \
#   blur_radius=30 \
#   color=0x40000000 \
#   border_color=0x40000000 \
#   border_width=1 \
#   padding_left=32 \
#   padding_right=32 \
#   shadow.drawing=on
# Can not keep comments in the
# height=38 \
# height=24 \
##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="FiraCode Nerd Font Mono:Normal:18.0"
  label.font="FiraCode Nerd Font Mono:Normal:16.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  label.padding_left=2
  label.padding_right=2
)
sketchybar --default "${default[@]}"

##### Adding Left Items #####
# Active app

# https://felixkratz.github.io/SketchyBar/config/items
# sketchybar --add item chevron left \
#   --set chevron icon=󰅁 \
#   label.drawing=off \
#   icon.font="FiraCode Nerd Font:Normal:16.0" \
#   padding_right=0

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

# Right items
sketchybar --add item clock right \
  --set clock update_freq=10 icon= icon.font="Hack Nerd Font:Normal:12.0" script="$PLUGIN_DIR/clock.sh"

sketchybar --add item dash right \
  --set dash \
  label="|" \
  label.padding_left=0 \
  label.padding_left=0 \
  icon.drawing=off

sketchybar --add item aerospace_workspace right --set aerospace_workspace label="1" label.padding_right=0 label.padding_left=0 icon.drawing=off

sketchybar --add item dash2 right \
  --set dash2 \
  label="|" \
  icon.drawing=off

sketchybar --add item front_app right \
  --set front_app script="$PLUGIN_DIR/front_app.sh" \
  label.padding_right=0 \
  label.padding_left=0 \
  --subscribe front_app front_app_switched

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
