# Example aliases
# Note format
# No spaces between name and string
# alias <name>=<string>

# Default editor
editor="code"
aliases_file=$dotfile_dir/aliases.sh

# Restarts shell
# Call after making changes w/o having to restart
alias refresh="source ~/.bashrc && clear"
alias r="refresh"

# Google docs
alias doc="python -mwebbrowser https://docs.google.com/create" # New google doc
alias docs="python -mwebbrowser http://docs.google.com"        # Main docs folder

# Git
alias conflicts="git diff --name-only --diff-filter=U"          # Does not push
alias no-edit="git commit --amend --no-edit"                    # Does not push
alias last="git log -1"                                         # Show last change
alias rebase="git fetch upstream && git rebase upstream/master" # Fetch and rebase
alias gcane!="git add -A && git commit --amend --no-edit && git push -f"

# System
alias off="sudo shutdown -h now"    # Shutdown
alias sleep="pmset sleepnow"        # Sleep

# Open dotfiles
alias dotfiles="${editor} $dotfile_dir"
alias aliases="${editor} $aliases_file"
alias dot="cd $dotfile_dir"
alias n="npm start"
alias p="cd ${work}"
alias halp="cat ~/dotfiles/aliases.sh"
alias a="${editor} ~/dotfiles/aliases.sh"

# Created from bookmark or new-alias
alias v="vim ."
alias grc="git rebase --continue"
alias nt="npm test"
alias gfu="git fetch upstream"
alias m="git checkout master"
alias stash="git stash"
alias ni="npm install"
alias ga="git add ."
alias gcane="commit --amend --no-edit"
alias gcane="git commit --amend --no-edit"
alias clean="rm -rf node_modules && npm install"
alias liquid-docs="open https://shopify.github.io/liquid/tags/control-flow/"
alias diff="git diff"
alias p="cd ~/Documents/Projects/"
alias xyz="cd ~/Documents/Projects/xyz"
alias xyzb="cd ~/Documents/Projects/fisterra-backend"
alias ys="yarn start"
alias gco="git checkout"
alias gcof="git checkout --"
alias grem="git remote"
alias gp="git push"
alias gl="git log -1"
alias yb="yarn build"
alias ya="yarn add"
alias rf="rm -rf"
alias yys="yarn && yarn start"
alias yc="yarn clean"
alias halp="cat ~/dotfiles/aliases.sh"
alias e="cd /c/Users/huapa/Documents/Projects/evan-client"
alias ns="npm start"
alias es="cd /c/Users/huapa/Documents/Projects/evan-server"
alias ea="e && a"
alias conflicts="git diff --name-only --diff-filter=U"
alias yd="yarn dev"
alias gf="git fetch"
alias gcc="gcof ./src/config/axios.js"
alias gb="git branch"
alias staging="gco staging"
alias gac="git add . && git commit -m"
alias gs="git stash"
alias gr!="git reset --hard"
alias gfp="git fetch && git pull"
alias yr="yarn run"
alias sl="export ENVIRONMENT=windows&&sails lift"
alias yrw="export ENVIRONMENT=windows&&sails lift"
alias wip="gap ':construction:'"
alias ddac="cd /c/Users/huapa/Documents/Projects/dallas-design-and-code-slides"
alias mk="mkdir ${2} && cd ${2}"
alias ea="cd /c/Users/huapa/Documents/Projects/mk/electron-app"
alias gm="git merge -m ':octocat:'"
alias bsw="cd /c/Users/huapa/Documents/Projects/bisonstudio-v2.0"
alias rm!="rm -rf"
alias grs="git rebase origin/staging"
alias gd="git diff"
alias gcat="gap ":octocat:""
alias undo="git reset HEAD~1"
alias rs="cd /c/Users/huapa/Documents/Projects/React-Wordpress-Starter-Kit"
alias sparkles="git add . && git commit -m ':sparkles: ' && git push"
alias s="git checkout staging"
alias n="npm"
alias r!="rm -rf"
alias build="npm run build"
alias cpr="cp -rf"
alias crb="cordova run browser"
alias s="python -m http.server"
alias la="ls -a"
alias y="yarn"
alias cpa="cordova platform add"
alias cpab="cordova add platform browser"
alias cpab="cordova platform add browser"
alias c="cordova"
alias ba="build && android"
alias and="cd ./cordova && cordova run android && cd .."
alias ec="cd /c/Users/huapa/Documents/Projects/evan-client/cordova"
alias ba="yr cordova-build && and"
alias cra="cordova run android"
alias yrc="yarn run cordova-build"
alias ba="yrc && and"
alias copy="rm -rf ./cordova/www/* && cp -rf ./build/* ./cordova/www"
alias static="-p"
alias static="static -p 8000"
alias grs="grunt serve"
alias bs="build && cd build && static && .."
alias h="heroku"
alias hl="heroku logs --tail --app bison-studio-web"
alias co="code ./"
alias ycb="yarn run cordova-build"
alias cpr="cordova platforms rm"
alias cpca="cordova platforms rm android && cordova platforms add androidf"
alias cpa="cordova platforms add"
alias grs="git rebase origin/staging"
alias t="cd /c/Users/huapa/Documents/Projects/tilde"
alias yrd="yarn run dev"
alias sl="sails lift"
alias d="cd ~/dotfiles"
alias yrd="yarn run devan-start"
alias status="git status"
alias mvwww="rm -rf ./cordova/www/* && cp -rf ./build/* ./cordova/www"
alias w="rm -rf ./cordova/www/* && cp -rf ./build/* ./cordova/www"
alias yrw="ENVIRONMENT=development DATABASE_ENVIRONMENT=windows sails lift"
alias yrwk="KEEP_DB=true ENVIRONMENT=development DATABASE_ENVIRONMENT=windows sails lift"
alias waffle="start https://waffle.io/GooberLLC/evan-project"
alias sl="cd /c/Users/huapa/Documents/Projects/Speakeasy-landing"
alias rsl="cross-env KEEP_DB=true sails lift"
alias dotfiles="co ~/dotfiles"
alias ec="cd /c/Users/huapa/Documents/Projects/evan-client"
alias ec="cd /c/Users/huapa/Documents/Projects/evan-client/cordova"
alias e="cd /c/Users/Devan/Documents/Projects/evan-client"
alias gcg="git config --global"
alias cpra="cordova platforms remove android"
alias cpaa="cordova platforms add android"
alias log="git log"
alias sl="KEEP_DB=true sails lift"
alias cs="yarn run cordova-staging-build"
alias cb="yarn run cordova-production-build"
alias rmr="rm -rf"
alias nrsr="npm run start-renderer-dev"
alias nrsm="npm run start-main-dev"
alias ni!="ni && npm i axios && npm rbuild-node-sass"
alias ysr="yarn run start-renderer-dev"
alias ysm="yarn run start-main-dev"
alias spk="cd /c/Users/huapa/Documents/Projects/speakeasy"
alias e="cd /c/Users/huapa/Documents/Projects/evan-client"
alias ncsb="npm run cordova-staging-build"
alias ncb="npm run cordova-production-build"
alias cpls="cordova platforms ls"
alias nsr="npm run start-render-dev"
alias nsm="npm run start-main-dev"
alias nsr="start-renderer-dev"
alias nrd="npm run develop"
alias mkl="cd /c/Users/huapa/Documents/Projects/majorkey-landing-page"
alias nrd="npm run dev"
alias mk="cd /c/Users/huapa/Documents/Projects/majorkey"
alias nsr="npm run start-renderer-dev"
alias cpb="npm run cordova-production-build"
alias csb="cordova-staging-build"
alias csb="npm run cordova-staging-build"
alias cpra="cordova platforms remove android"
alias cpaa="cordova platforms add android"
alias open="explorer"
alias o="open ./"
alias ts="cat /c/Users/huapa/Documents/Projects/tinder-script.js > /dev/clipboard"
alias tsc="code /c/Users/huapa/Documents/Projects/tinder-script.js"
alias e2="cd /c/Users/huapa/Documents/Projects/ec2"
alias cor="cd /c/Users/huapa/Documents/Projects/evan-client/cordova"
alias cpa="cpra && cpaa"
alias conf="conflicts"
alias d="cd /c/Users/huapa/Documents/Projects/devan.gg"
alias dot="cd /c/Users/huapa/dotfiles"
alias gms="git merge staging"
alias gmc="git merge --continue"
alias es2="cd /c/Users/huapa/Documents/Projects/es2"
alias cclean="rm node_modules plugins platforms package-lock.json && npm i -s && cordova platforms add android"
alias cclean="rm -rf node_modules plugins platforms package-lock.json && npm i -s && cordova platforms add android"
alias cpca="cpra && rm package-lock.json && cpaa"
alias cba="cordova build android"
alias cord="cp cordova"
alias cord="cd ./cordova"
alias gt="cd /c/Users/huapa/Documents/Projects/gatsby-projects/good-tooday"
alias rc="rm -rf .cache"
alias bld="npm run build"
alias gt="cd /c/Users/huapa/Documents/Projects/gatsby-projects/good-today"
alias sa="cd /c/Users/huapa/Documents/Projects/gatsby-projects/gatsby/examples/simple-auth"
alias un="npm un -s"
alias gd="GATSBY_GA_TRACKING_ID='UA-128499326-1' GATSBY_STRIPE_PK='pk_test_AO5DnEdWNNGhfMgOTUZxm1WA' GATSBY_SITE_URL='https://good-today.netlify.com' GATSBY_API_URL='https://api.goodtoday.org/' GATSBY_API_AUTH_HEADER='Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTM5MjcxMzkwLCJleHAiOjE1Mzk4NzYxOTB9.AV6fipoLpaXLT75TESDhaRuHTk7ulkYqKQVhaapUqZA' gatsby develop"
