# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders

    gaps_in = 0
    gaps_out = 0
    # border_size = 0
    border_size = 1
 
    gaps_in = 2
    gaps_out = 4
    # border_size = 1

    # gaps_in = 16
    # gaps_out = 124

    # border_size = 2
  
    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    # No ansi support for overrides, unfortunately
    # col.active_border = rgba(52CFFFFF)
    # col.active_border = rgba(94C7C8FF)
    # col.active_border = rgba(FEC4FFFF)
    # col.active_border = rgba(E2C264FF)
    # col.active_border = rgba(FFFFFF22)

    # gaps_in = 4
    # gaps_out = 24
    # border_size = 1

    # gaps_in = 8
    # gaps_out = 64
    # border_size = 2

    # Use master layout instead of dwindle
    # layout = master
}

xwayland {
  force_zero_scaling = true
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 0
    # rounding = 14
    # rounding = 8
    # rounding = 4
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1.6 1
}
