brew "neovim"
brew "fzf"
brew "zoxide"
brew "ripgrep"
brew "nvm"
brew "gh"

# terminal goodies
brew "tmux"

# Docker alternative
brew "colima"

tap "homebrew/cask"
brew "aerospace"
brew "font-fira-code-nerd-font"
brew "docker"
brew "orbstack
