#!/bin/bash

# https://github.com/FelixKratz/JankyBorders
#
# https://github.com/FelixKratz/JankyBorders/wiki/Man-Page

#	style=round
options=(
  style=square
  width=6
  hidpi=on
  active_color=0x88ff69b4
  inactive_color=0xff414550
)

borders "${options[@]}"
