#!/bin/bash

# https://github.com/FelixKratz/JankyBorders
#
# https://github.com/FelixKratz/JankyBorders/wiki/Man-Page

#	style=round
# active_color=0x88ff69b4
# 'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
options=(
  style=round
  width=5
  hidpi=on
  active_color=0xeeff69b4
  inactive_color=0xff414550
)

borders "${options[@]}"
