
[gaps]
    inner.horizontal = 16
    inner.vertical =   16
    outer.left =       32
    outer.bottom =     32
    outer.top =        32 
    outer.right =      32 
    # inner.horizontal = 16
    # inner.vertical =   16
    # outer.left =       64
    # outer.bottom =     64
    # outer.top =        64 
    # outer.right =      64 
    # inner.horizontal = 8
    # inner.vertical =   8
    # outer.left =       8
    # outer.bottom =   648
    # outer.top =        8
    # outer.right =      8
    # enable_for_floating = true  # this is the key line
    # inner_gap = 8         # space between tiled windows
    # outer_gap = 8         # space around the screen edge

