console_title_template = '{{ .Folder }}'
version = 3

[transient_prompt]
  template = ' '
  foreground = '#FEF5ED'
  background = 'transparent'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    leading_diamond = '<#ff70a6>  </>'
    template = '{{ .UserName }} <#ffffff>on</>'
    foreground = '#ffbebc'
    type = 'session'
    style = 'diamond'

    [blocks.segments.properties]
      display_host = true

  [[blocks.segments]]
    template = ' {{ .CurrentDate | date .Format }} '
    foreground = '#bc93ff'
    type = 'time'
    style = 'diamond'

    [blocks.segments.properties]
      time_format = 'Monday <#ffffff>at</> 3:04 PM'

  [[blocks.segments]]
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = '#ee79d1'
    type = 'git'
    style = 'diamond'

    [blocks.segments.properties]
      branch_icon = ' '
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true
      fetch_worktree_count = true

  [[blocks.segments]]
    leading_diamond = '<#00c7fc>  </><#ffafd2>{</>'
    trailing_diamond = '<#ffafd2>}</>'
    template = '  {{ .Path }} '
    foreground = '#ffafd2'
    type = 'path'
    style = 'diamond'
    
[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    foreground = '#a9ffb4'
    type = 'text'
    style = 'plain'

  [[blocks.segments]]
    template = ' {{ .FormattedMs }}s <#ffffff></>'
    foreground = '#a9ffb4'
    type = 'executiontime'
    style = 'diamond'

    [blocks.segments.properties]
      style = 'dallas'
      threshold = 0.0

  [[blocks.segments]]
    template = '  '
    type = 'root'
    style = 'diamond'

    [blocks.segments.properties]
      root_icon = ' '

  [[blocks.segments]]
    template = ' <#ffffff>MEM:</> {{ round .PhysicalPercentUsed .Precision }}% ({{ (div ((sub .PhysicalTotalMemory .PhysicalAvailableMemory)|float64) 1073741824.0) }}/{{ (div .PhysicalTotalMemory 1073741824.0) }}GB)'
    foreground = '#94ffa2'
    type = 'sysinfo'
    style = 'diamond'

    [blocks.segments.properties]
      folder_icon = ''
      folder_separator_icon = '  '
      home_icon = 'home'
      style = 'agnoster_full'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '  '
    foreground = '#A9FFB4'
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}#ef5350{{ end }}']
    newline = true
  
    [blocks.segments.properties]
      always_enabled = true
      # text = '\n'
