# Bubbles theme updated to catppuccin colors
# https://catppuccin.com/palette/
# https://github.com/ohmyposh/ohmyposh/blob/main/themes/bubbles.toml
# https://github.com/catppuccin/oh-my-posh/blob/main/themes/catppuccin.toml
# 
# oh my posh references:
# https://ohmyposh.dev/docs/configuration/colors

version = 3
final_space = true
# console_title_template = "{{.Folder}}{{if .Root}} :: root{{end}} :: {{.Shell}}"
# console_title_template = "{{.Folder}}"
console_title_template = '{{.PWD}}'


[palette]
  base = '#eff1f5'
  blue = '#8AADF4'
  lavender = '#B7BDF8'
  os = '#ACB0BE'
  pink = '#F5BDE6'
  text = '#494D64'
  wight = '#FFFFFF'
  rosewater = '#dc8a78'
  mauve = '#8839ef'
  green = '#40c4ff'
  maroon = '#e64553'
  sky = '#04a5e5'
  teal = '#40c4ff'
  yellow = '#e6c35c'
  orange = '#fe640b'
  red = '#e64553'
  violet = '#8839ef'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

# Insert blank line
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  force = true
  newline = true

  [[blocks.segments]]
    template = ' '
    type = 'text'
    style = 'plain'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ' '
    template = '{{ .UserName }}'
    foreground = 'p:text'
    background = 'p:blue'
    type = 'session'
    style = 'diamond'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .Path }}'
    foreground = 'p:text'
    background = 'p:pink'

    type = 'path'
    style = 'diamond'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ .HEAD }}'
    foreground = 'p:text'
    background = 'p:lavender'
    type = 'git'
    style = 'diamond'

    [blocks.segments.properties]
      branch_icon = ' '
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = false
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}'
    foreground = '#E4F34A'
    background = '#29315A'
    type = 'python'
    style = 'diamond'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
    foreground = '#7FD5EA'
    background = '#29315A'
    type = 'go'
    style = 'diamond'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}'
    foreground = '#42E66C'
    background = '#29315A'
    type = 'node'
    style = 'diamond'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
    foreground = '#E64747'
    background = '#29315A'
    type = 'ruby'
    style = 'diamond'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
    foreground = '#E64747'
    background = '#29315A'
    type = 'java'
    style = 'diamond'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#9B6BDF'
    background = '#29315A'
    type = 'julia'
    style = 'diamond'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}'
    foreground = 'p:base'
    background = 'p:sky'
    type = 'battery'
    style = 'diamond'
    # foreground_templates = ['{{if eq "Charging" .State.String}}p:base{{end}}', '{{if eq "Discharging" .State.String}}p:base{{end}}', '{{if eq "Full" .State.String}}p:base{{end}}']

    [blocks.segments.properties]
      charged_icon = ' '
      charging_icon = '⇡ '
      discharging_icon = '⇣ '

# Insert blank line
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true
  force = true

  [[blocks.segments]]
    template = ' '
    type = 'text'
    style = 'plain'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ' '
    template = '{{ .FormattedMs }}'
    foreground = '#AEA4BF'
    background = '#29315A'
    type = 'executiontime'
    style = 'diamond'

    [blocks.segments.properties]
      style = 'austin'
      threshold = 150

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ' '
    template = '❯'
    foreground = 'p:pink'
    type = 'text'
    style = 'diamond'
